# generated by datamodel-codegen:
#   filename:  cohort.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    admin: bool | None = None
    authorities: list[str] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None


class Authority(BaseModel):
    name: str | None = None


class CohortSequenceType(Enum):
    NUMERIC = 'NUMERIC'
    STRING = 'STRING'


class CohortSequenceDTO(BaseModel):
    cohortSequenceNumericValue: int | None = None
    cohortSequenceStringValue: str | None = None
    cohortSequenceType: CohortSequenceType | None = None


class DateFilterDTO(BaseModel):
    greaterThan: AwareDatetime | None = None
    lowerThan: AwareDatetime | None = None


class CohortType(Enum):
    ENCOUNTER = 'ENCOUNTER'
    PATIENT = 'PATIENT'


class EdsCohortCreationDTO(BaseModel):
    cohortDescription: str | None = None
    cohortName: str | None = None
    cohortSequenceDTO: CohortSequenceDTO | None = None
    cohortType: CohortType | None = None
    projectId: str | None = None


class NumericComparator(Enum):
    BETWEEN = 'BETWEEN'
    EQUALS = 'EQUALS'
    INFERIOR = 'INFERIOR'
    INFERIOR_OR_EQUALS = 'INFERIOR_OR_EQUALS'
    NOT_EQUAL = 'NOT_EQUAL'
    SUPERIOR = 'SUPERIOR'
    SUPERIOR_OR_EQUALS = 'SUPERIOR_OR_EQUALS'


class I2b2NumericFilter(BaseModel):
    numericBetweenValue: float | None = None
    numericComparator: NumericComparator | None = None
    numericValue: float | None = None
    unitValue: str | None = None
    valueFlagValue: str | None = None


class I2b2Paths(BaseModel):
    conceptPath: str | None = None
    id: int | None = None
    modifierPath: str | None = None


class QueryResultType(Enum):
    ENCOUNTER_NUM = 'ENCOUNTER_NUM'
    PATIENT_NUM = 'PATIENT_NUM'


class QueryType(Enum):
    NON_TEMPORAL = 'NON_TEMPORAL'
    SAME_ENCOUNTER = 'SAME_ENCOUNTER'


class UnitValue(Enum):
    MONTH = 'MONTH'
    YEAR = 'YEAR'


class I2b2TemporalFilter(BaseModel):
    numericBetweenValue: float | None = None
    numericComparator: NumericComparator | None = None
    numericValue: float | None = None
    unitValue: UnitValue | None = None
    valueFlagValue: str | None = None


class PseudonymizerResponseDTO(BaseModel):
    identitiesAlreadyPseudonymedCount: int | None = None
    identitiesDuplicateCount: int | None = None
    identitiesRecivedCount: int | None = None
    identityPseudonymGroup: str | None = None
    newPseudomizedIdentitiesCount: int | None = None
    pseudonymIdentities: list[str] | None = None
    wrongIdentitiesCount: int | None = None


class QueryStatus(Enum):
    ABORTED = 'ABORTED'
    FINISHED = 'FINISHED'
    IN_PROGRESS = 'IN_PROGRESS'


class QueryExecution(BaseModel):
    authorizedEncounterCount: int | None = None
    authorizedPatientCount: int | None = None
    encounterCount: int | None = None
    executionDate: AwareDatetime | None = None
    id: str | None = None
    obfuscated: bool | None = None
    patientCount: int | None = None
    pseudonomyzerResponse: PseudonymizerResponseDTO | None = None
    queryStatus: QueryStatus | None = None
    resultDate: AwareDatetime | None = None


class SchedulingEnum(Enum):
    BIMONTHLY = 'BIMONTHLY'
    BIWEEKLY = 'BIWEEKLY'
    DALY = 'DALY'
    MONTHLY = 'MONTHLY'
    QUARTERLY = 'QUARTERLY'
    SEMI_ANNUALLY = 'SEMI_ANNUALLY'
    WEEKLY = 'WEEKLY'
    YEARLY = 'YEARLY'


class Purpose(Enum):
    OPERATIONAL_SUPPORT = 'OPERATIONAL_SUPPORT'
    OTHER = 'OTHER'
    PRACTICE = 'PRACTICE'
    QUALITY_IMPROVEMENT = 'QUALITY_IMPROVEMENT'
    RESEARCH = 'RESEARCH'


class RedCAPInstanceEnum(Enum):
    CHU_REDCAP = 'CHU_REDCAP'
    IAMREDCAP = 'IAMREDCAP'
    IHUREDCAP = 'IHUREDCAP'
    USMR_REDCAP = 'USMR_REDCAP'


class REDCapProject(BaseModel):
    fieldCount: int | None = None
    instrumentCount: int | None = None
    pid: int | None = None
    projectNotes: str | None = None
    projectTitle: str | None = None
    purpose: Purpose | None = None
    purposeOther: str | None = None
    recordCount: int | None = None
    redCAPInstanceEnum: RedCAPInstanceEnum | None = None
    token: str | None = None
    url: str | None = None
    version: str | None = None


class REDCapProjectCreationDTO(BaseModel):
    projectNotes: str | None = None
    projectTitle: str | None = None
    purpose: Purpose | None = None
    purposeOther: str | None = None


class REDCapProjectWithoutTokenDTO(BaseModel):
    fieldCount: int | None = None
    instrumentCount: int | None = None
    pid: int | None = None
    projectNotes: str | None = None
    projectTitle: str | None = None
    purpose: Purpose | None = None
    purposeOther: str | None = None
    recordCount: int | None = None
    redCAPInstanceEnum: RedCAPInstanceEnum | None = None
    url: str | None = None
    version: str | None = None


class Role(Enum):
    ADD_IDENTITIES = 'ADD_IDENTITIES'
    ADD_PARTICIPANTS = 'ADD_PARTICIPANTS'
    COHORT_ADMINISTRATOR = 'COHORT_ADMINISTRATOR'
    COHORT_PARTICIPANT = 'COHORT_PARTICIPANT'
    GET_LINK_CROSS_COHORT = 'GET_LINK_CROSS_COHORT'
    GET_PSEUDONYM_COHORT = 'GET_PSEUDONYM_COHORT'
    GET_UNPSEUDONYM_COHORT = 'GET_UNPSEUDONYM_COHORT'
    REMOVE_IDENTITIES = 'REMOVE_IDENTITIES'
    REMOVE_PARTICIPANTS = 'REMOVE_PARTICIPANTS'
    SET_ROLE_TO_USER = 'SET_ROLE_TO_USER'


class User(BaseModel):
    activated: bool | None = None
    authorities: list[Authority] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class CohortSequence(BaseModel):
    cohortSequenceNumericValue: int | None = None
    cohortSequenceStringValue: str | None = None
    cohortSequenceType: CohortSequenceType | None = None
    createdBy: User | None = None
    createdDate: AwareDatetime | None = None
    deleted: bool | None = None
    deletedBy: User | None = None
    deletedDate: AwareDatetime | None = None
    id: str | None = None


class I2b2Criteria(BaseModel):
    ageAtStartVisitFilter: I2b2TemporalFilter | None = None
    ageAtStartVisitInMonthFilter: I2b2NumericFilter | None = None
    endDateFilter: DateFilterDTO | None = None
    i2b2Paths: list[I2b2Paths] | None = None
    id: int | None = None
    label: str | None = None
    labelAscendant: str | None = None
    nvalNumFilter: I2b2NumericFilter | None = None
    observationBlobFilters: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    type: str | None = None


class I2b2PanelTemplate(BaseModel):
    i2b2Criterias: list[I2b2Criteria] | None = None
    id: int | None = None


class I2b2QueryTemplate(BaseModel):
    createdBy: User | None = None
    creationDate: AwareDatetime | None = None
    id: str | None = None
    notPanel: I2b2PanelTemplate | None = None
    panels: list[I2b2PanelTemplate] | None = None
    queryName: str | None = None
    queryResultType: QueryResultType | None = None
    queryType: QueryType | None = None


class QueryScheduler(BaseModel):
    active: bool | None = None
    createdBy: User | None = None
    creationDate: AwareDatetime | None = None
    deleted: bool | None = None
    i2b2QueryTemplate: I2b2QueryTemplate | None = None
    id: str | None = None
    lastScheduling: AwareDatetime | None = None
    nextScheduling: AwareDatetime | None = None
    queryExecutions: list[QueryExecution] | None = None
    schedulingEnum: SchedulingEnum | None = None


class Role2(BaseModel):
    createdBy: User | None = None
    createdDate: AwareDatetime | None = None
    id: str | None = None
    role: Role | None = None


class UserRoles(BaseModel):
    activated: bool | None = None
    authorities: list[Authority] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None
    roles: list[Role2] | None = None


class EdsCohort(BaseModel):
    cohortDescription: str | None = None
    cohortName: str | None = None
    cohortSequence: CohortSequence | None = None
    cohortType: CohortType | None = None
    createdBy: User | None = None
    creationDate: AwareDatetime | None = None
    id: str | None = None
    identityPseudonymGroup: str | None = None
    projectId: str | None = None
    pseudonymIdentities: list[str] | None = None
    querySchedulers: list[QueryScheduler] | None = None
    redcap: REDCapProject | None = None
    smartCrfTaskId: int | None = None
    userRoles: list[UserRoles] | None = None


class EdsCohortDTO(BaseModel):
    cohortDescription: str | None = None
    cohortName: str | None = None
    cohortSequence: CohortSequence | None = None
    cohortType: CohortType | None = None
    createdBy: User | None = None
    creationDate: AwareDatetime | None = None
    id: str | None = None
    identityPseudonymGroup: str | None = None
    projectId: str | None = None
    pseudonymIdentities: list[str] | None = None
    querySchedulers: list[QueryScheduler] | None = None
    redcap: REDCapProjectWithoutTokenDTO | None = None
    smartCrfTaskId: int | None = None
    userRoles: list[UserRoles] | None = None
