# generated by datamodel-codegen:
#   filename:  management.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel


class FilterDefinition(BaseModel):
    args: dict[str, str] | None = None
    name: str


class PredicateDefinition(BaseModel):
    args: dict[str, str] | None = None
    name: str


class PublisherOfResponseEntityOfobject(BaseModel):
    pass


class RouteDefinition(BaseModel):
    filters: list[FilterDefinition] | None = None
    id: str | None = None
    metadata: dict[str, Any] | None = None
    order: int | None = None
    predicates: list[PredicateDefinition] | None = None
    uri: AnyUrl
