# generated by datamodel-codegen:
#   filename:  path_filter.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, constr


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    authorities: list[str] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: constr(min_length=5, max_length=254) | None = None
    firstName: constr(min_length=0, max_length=50) | None = None
    id: str | None = None
    imageUrl: constr(min_length=0, max_length=256) | None = None
    langKey: constr(min_length=2, max_length=10) | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: constr(min_length=0, max_length=50) | None = None
    login: constr(
        pattern=r'^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$',
        min_length=1,
        max_length=50,
    )


class I2b2PathPropertyEntry(BaseModel):
    dataElementDomain: bool | None = None
    descendant: bool | None = None
    iri: str | None = None
    leafDomain: bool | None = None
    order: int | None = None
    permissibleValue: bool | None = None
    rootRange: bool | None = None
    transitive: bool | None = None


class I2b2PathfilterRootIris(BaseModel):
    iri: str | None = None
    isCategory: bool | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class I2b2PathBuilderEntry(BaseModel):
    i2b2PathPropertyEntries: list[I2b2PathPropertyEntry] | None = None
    rootIris: list[I2b2PathfilterRootIris] | None = None


class I2b2PathModifierFilter(BaseModel):
    activeFilter: bool | None = None
    i2b2PathBuilderEntries: list[I2b2PathBuilderEntry] | None = None
    id: str | None = None
    modifiedNode: str | None = None
    modifierPaths: list[I2b2PathModifierFilter] | None = None
    rootNodeLabel: str | None = None
    tableName: str | None = None


class EDSPathFilter(BaseModel):
    activeFilter: bool | None = None
    i2b2PathBuilderEntries: list[I2b2PathBuilderEntry] | None = None
    id: str | None = None
    modifierPaths: list[I2b2PathModifierFilter] | None = None
    rootNodeLabel: str | None = None
    tableName: str | None = None


I2b2PathModifierFilter.model_rebuild()
