# generated by datamodel-codegen:
#   filename:  pseudonymizer.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, AwareDatetime, BaseModel


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    admin: bool | None = None
    authorities: list[str] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None


class IdentityType(Enum):
    ENCOUNTER_NUM = 'ENCOUNTER_NUM'
    NDA = 'NDA'
    NIP = 'NIP'
    PATIENT_NUM = 'PATIENT_NUM'


class EdsIdentityDTO(BaseModel):
    encounterIdentityValue: str | None = None
    identityType: IdentityType | None = None
    patientIdentityValue: str | None = None


class EdsPseudonymIdentity(BaseModel):
    allPatientIdentityValues: list[str] | None = None
    edsIdentitiesBasedOnIdentityType: str | None = None
    encounterIdentityValue: str | None = None
    id: str | None = None
    identityPseudonym: str | None = None
    identityPseudonymGroup: str | None = None
    identityType: IdentityType | None = None
    patientIdentityValue: str | None = None
    patientMasterIdentityValue: str | None = None


class SequenceType(Enum):
    NUMERIC = 'NUMERIC'
    STRING = 'STRING'


class EdsPseudonymSequenceManager(BaseModel):
    createdDate: AwareDatetime | None = None
    id: int | None = None
    identityPseudonymGroup: str | None = None
    sequenceNumericValue: int | None = None
    sequenceStringValue: str | None = None
    sequenceType: SequenceType | None = None


class EdsPseudonymSequenceManagerDTO(BaseModel):
    sequenceNumericValue: int | None = None
    sequenceStringValue: str | None = None
    sequenceType: SequenceType | None = None


class InputStream(BaseModel):
    pass


class InputStreamResource(BaseModel):
    description: str | None = None
    file: bytes | None = None
    filename: str | None = None
    inputStream: InputStream | None = None
    open: bool | None = None
    readable: bool | None = None
    uri: AnyUrl | None = None
    url: str | None = None


class NumericalUnivariateStatisticDTO(BaseModel):
    count: int | None = None
    max: float | None = None
    mean: float | None = None
    median: float | None = None
    min: float | None = None
    q1: float | None = None
    q3: float | None = None
    sd: float | None = None
    sum: float | None = None


class PseudonymizerIdentitySequenceDTO(BaseModel):
    identitiesDto: list[EdsIdentityDTO] | None = None
    pseudonymSequenceManagerDto: EdsPseudonymSequenceManagerDTO | None = None


class PseudonymizerResponseDTO(BaseModel):
    identitiesAlreadyPseudonymedCount: int | None = None
    identitiesDuplicateCount: int | None = None
    identitiesRecivedCount: int | None = None
    identityPseudonymGroup: str | None = None
    newPseudomizedIdentitiesCount: int | None = None
    pseudonymIdentities: list[str] | None = None
    wrongIdentitiesCount: int | None = None


class ResultAggregateDataDTO(BaseModel):
    label: str | None = None
    value: str | None = None


class Sort(BaseModel):
    empty: bool | None = None
    sorted: bool | None = None
    unsorted: bool | None = None


class UnpseudonymIdentityDTO(BaseModel):
    empty: bool | None = None
    present: bool | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class PageOfEdsPseudonymIdentity(BaseModel):
    content: list[EdsPseudonymIdentity] | None = None
    empty: bool | None = None
    first: bool | None = None
    last: bool | None = None
    number: int | None = None
    numberOfElements: int | None = None
    size: int | None = None
    sort: Sort | None = None
    totalElements: int | None = None
    totalPages: int | None = None


class PseudonymGroupDescriptionDTO(BaseModel):
    ageAtDeathDesc: NumericalUnivariateStatisticDTO | None = None
    ageAtLastEncounterDesc: NumericalUnivariateStatisticDTO | None = None
    ageAtLastEncounterHistogram: list[ResultAggregateDataDTO] | None = None
    count: int | None = None
    encounterCountDesc: NumericalUnivariateStatisticDTO | None = None
    sex: list[ResultAggregateDataDTO] | None = None
    vitalStatus: list[ResultAggregateDataDTO] | None = None
    yearsSinceLastVisit: list[ResultAggregateDataDTO] | None = None
