# generated by datamodel-codegen:
#   filename:  query_builder.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    admin: bool | None = None
    authorities: list[str] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None


class Authority(BaseModel):
    name: str | None = None


class DateFilterDTO(BaseModel):
    greaterThan: AwareDatetime | None = None
    lowerThan: AwareDatetime | None = None


class NumericComparator(Enum):
    BETWEEN = 'BETWEEN'
    EQUALS = 'EQUALS'
    INFERIOR = 'INFERIOR'
    INFERIOR_OR_EQUALS = 'INFERIOR_OR_EQUALS'
    NOT_EQUAL = 'NOT_EQUAL'
    SUPERIOR = 'SUPERIOR'
    SUPERIOR_OR_EQUALS = 'SUPERIOR_OR_EQUALS'


class I2b2NumericFilter(BaseModel):
    numericBetweenValue: float | None = None
    numericComparator: NumericComparator | None = None
    numericValue: float | None = None
    unitValue: str | None = None
    valueFlagValue: str | None = None


class I2b2Paths(BaseModel):
    conceptPath: str | None = None
    id: int | None = None
    modifierPath: str | None = None


class QueryResultType(Enum):
    ENCOUNTER_NUM = 'ENCOUNTER_NUM'
    PATIENT_NUM = 'PATIENT_NUM'


class QueryStatus(Enum):
    ABORTED = 'ABORTED'
    FINISHED = 'FINISHED'
    IN_PROGRESS = 'IN_PROGRESS'


class QueryType(Enum):
    NON_TEMPORAL = 'NON_TEMPORAL'
    SAME_ENCOUNTER = 'SAME_ENCOUNTER'


class UnitValue(Enum):
    MONTH = 'MONTH'
    YEAR = 'YEAR'


class I2b2TemporalFilter(BaseModel):
    numericBetweenValue: float | None = None
    numericComparator: NumericComparator | None = None
    numericValue: float | None = None
    unitValue: UnitValue | None = None
    valueFlagValue: str | None = None


class PseudonymizerResponseDTO(BaseModel):
    identitiesAlreadyPseudonymedCount: int | None = None
    identitiesDuplicateCount: int | None = None
    identitiesRecivedCount: int | None = None
    identityPseudonymGroup: str | None = None
    newPseudomizedIdentitiesCount: int | None = None
    pseudonymIdentities: list[str] | None = None
    wrongIdentitiesCount: int | None = None


class ResultAggregateDataDTO(BaseModel):
    label: str | None = None
    value: str | None = None


class User(BaseModel):
    activated: bool | None = None
    authorities: list[Authority] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: str | None = None
    login: str | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class I2b2Criteria(BaseModel):
    ageAtStartVisitFilter: I2b2TemporalFilter | None = None
    ageAtStartVisitInMonthFilter: I2b2NumericFilter | None = None
    endDateFilter: DateFilterDTO | None = None
    i2b2Paths: list[I2b2Paths] | None = None
    id: int | None = None
    label: str | None = None
    labelAscendant: str | None = None
    nvalNumFilter: I2b2NumericFilter | None = None
    observationBlobFilters: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    type: str | None = None


class I2b2CriteriaDTO(BaseModel):
    ageAtStartVisitFilter: I2b2TemporalFilter | None = None
    endDateFilter: DateFilterDTO | None = None
    i2b2Paths: list[I2b2Paths] | None = None
    label: str | None = None
    labelAscendant: str | None = None
    nvalNumFilter: I2b2NumericFilter | None = None
    observationBlobFilters: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    type: str | None = None


class I2b2CriteriaReq(BaseModel):
    ageAtStartVisitFilter: I2b2TemporalFilter | None = None
    endDateFilter: DateFilterDTO | None = None
    i2b2Paths: list[I2b2Paths] | None = None
    id: int | None = None
    label: str | None = None
    labelAscendant: str | None = None
    nvalNumFilter: I2b2NumericFilter | None = None
    observationBlobFilters: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    type: str | None = None


class I2b2CriteriaRes(BaseModel):
    ageAtStartVisitFilter: I2b2TemporalFilter | None = None
    ageAtStartVisitInMonthFilter: I2b2NumericFilter | None = None
    endDateFilter: DateFilterDTO | None = None
    i2b2Paths: list[I2b2Paths] | None = None
    id: int | None = None
    label: str | None = None
    labelAscendant: str | None = None
    nvalNumFilter: I2b2NumericFilter | None = None
    observationBlobFilters: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    type: str | None = None


class I2b2Panel(BaseModel):
    cardinality: int | None = None
    i2b2Criterias: list[I2b2Criteria] | None = None
    id: int | None = None


class I2b2PanelDTO(BaseModel):
    cardinality: int | None = None
    i2b2Criterias: list[I2b2CriteriaDTO] | None = None
    id: int | None = None


class I2b2PanelReq(BaseModel):
    cardinality: int | None = None
    i2b2Criterias: list[I2b2CriteriaReq] | None = None
    id: int | None = None


class I2b2PanelRes(BaseModel):
    cardinality: int | None = None
    i2b2Criterias: list[I2b2CriteriaRes] | None = None
    id: int | None = None


class I2b2Query(BaseModel):
    authorizedEncounterCount: int | None = None
    authorizedPatientCount: int | None = None
    cohortId: str | None = None
    createdBy: User | None = None
    creationDate: AwareDatetime | None = None
    encounterCount: int | None = None
    encounterOppositionCount: int | None = None
    executionDate: AwareDatetime | None = None
    id: str | None = None
    notPanel: I2b2Panel | None = None
    obfuscated: bool | None = None
    oppositionPanel: I2b2Panel | None = None
    panels: list[I2b2Panel] | None = None
    patientCount: int | None = None
    patientOppositionCount: int | None = None
    projectId: str | None = None
    pseudonomyzerResponse: PseudonymizerResponseDTO | None = None
    queryName: str | None = None
    queryResultType: QueryResultType | None = None
    queryStatus: QueryStatus | None = None
    queryType: QueryType | None = None
    resultDate: AwareDatetime | None = None


class I2b2QueryDTO(BaseModel):
    notPanel: I2b2PanelDTO | None = None
    panels: list[I2b2PanelDTO] | None = None
    queryName: str | None = None
    queryResultType: QueryResultType | None = None
    queryType: QueryType | None = None
