# generated by datamodel-codegen:
#   filename:  .ipynb_checkpoints/main-checkpoint.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, constr


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    authorities: list[str] | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    email: constr(min_length=5, max_length=254) | None = None
    firstName: constr(min_length=0, max_length=50) | None = None
    id: str | None = None
    imageUrl: constr(min_length=0, max_length=256) | None = None
    langKey: constr(min_length=2, max_length=10) | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    lastName: constr(min_length=0, max_length=50) | None = None
    login: constr(
        pattern=r'^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$',
        min_length=1,
        max_length=50,
    )


class AuthInfoVM(BaseModel):
    clientId: str | None = None
    issuer: str | None = None


class EDSApplication(BaseModel):
    authorizedRole: str | None = None
    category: str | None = None
    cohortHandler: bool | None = None
    dataAnalyzer: bool | None = None
    defaultHidden: bool | None = None
    description: str | None = None
    id: str | None = None
    link: str | None = None
    logo: str | None = None
    logoContentType: str | None = None
    mySpaceApp: bool | None = None
    name: str | None = None
    needAuth: bool | None = None
    order: int | None = None
    projectManager: bool | None = None
    queryBuilder: bool | None = None


class ServiceInstance(BaseModel):
    host: str | None = None
    instanceId: str | None = None
    metadata: dict[str, str] | None = None
    port: int | None = None
    scheme: str | None = None
    secure: bool | None = None
    serviceId: str | None = None
    uri: AnyUrl | None = None


class User(BaseModel):
    activated: bool | None = None
    email: constr(min_length=5, max_length=254) | None = None
    firstName: constr(min_length=0, max_length=50) | None = None
    id: str | None = None
    imageUrl: constr(min_length=0, max_length=256) | None = None
    langKey: constr(min_length=2, max_length=10) | None = None
    lastName: constr(min_length=0, max_length=50) | None = None
    login: constr(
        pattern=r'^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$',
        min_length=1,
        max_length=50,
    )


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class ValidationRequest(BaseModel):
    clientId: str | None = None


class RouteVM(BaseModel):
    path: str | None = None
    serviceId: str | None = None
    serviceInstances: list[ServiceInstance] | None = None
