# generated by datamodel-codegen:
#   filename:  .ipynb_checkpoints/observation-checkpoint.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import AwareDatetime, BaseModel, conint


class IdentityType(Enum):
    PATIENT_NUM = 'PATIENT_NUM'
    ENCOUNTER_NUM = 'ENCOUNTER_NUM'
    NIP = 'NIP'
    NDA = 'NDA'


class EdsPseudonymIdentity(BaseModel):
    id: str | None = None
    identityPseudonym: str | None = None
    identityPseudonymGroup: str | None = None
    identityType: IdentityType | None = None
    patientIdentityValue: str | None = None
    allPatientIdentityValues: list[str] | None = None
    patientMasterIdentityValue: str | None = None
    encounterIdentityValue: str | None = None
    edsIdentitiesBasedOnIdentityType: str | None = None


class NumericalUnivariateStatisticDTO(BaseModel):
    count: int | None = None
    mean: float | None = None
    sd: float | None = None
    median: float | None = None
    q1: float | None = None
    q3: float | None = None
    min: float | None = None
    max: float | None = None
    sum: float | None = None


class ResultAggregateDataDTO(BaseModel):
    label: str | None = None
    value: str | None = None


class Pageable(BaseModel):
    page: conint(ge=0) | None = None
    size: conint(ge=1) | None = None
    sort: list[str] | None = None


class PseudonymPatientInfoDTO(BaseModel):
    pseudonymIdentityNum: str | None = None
    pseudonymIdentityNumMaster: str | None = None
    sexCd: str | None = None
    birthDate: date | None = None
    deathDate: date | None = None


class SortObject(BaseModel):
    empty: bool | None = None
    sorted: bool | None = None
    unsorted: bool | None = None


class EncounterSecurityLayerDTO(BaseModel):
    encounterNum: int | None = None
    authorization: int | None = None


class SecurityLayerDTO(BaseModel):
    ldapId: str | None = None
    patientNum: int | None = None
    maxDateAuthorized: AwareDatetime | None = None
    encounterSecurityLayers: list[EncounterSecurityLayerDTO] | None = None


class Operator(Enum):
    IN = 'IN'
    NOT_IN = 'NOT_IN'
    NOT_NULL = 'NOT_NULL'


class ColumnFilterDTO(BaseModel):
    elements: list[str] | None = None
    operator: Operator | None = None


class DateFilterDTO(BaseModel):
    greaterThan: AwareDatetime | None = None
    lowerThan: AwareDatetime | None = None


class ObservationFilterDTO(BaseModel):
    conceptCds: list[str] | None = None
    conceptPaths: list[str] | None = None
    modifierCds: list[str] | None = None
    modifierPaths: list[str] | None = None
    startDateFilter: DateFilterDTO | None = None
    endDateFilter: DateFilterDTO | None = None
    providerIdsFilter: ColumnFilterDTO | None = None
    observationBlobFilters: list[str] | None = None


class PseudonymObservationDTO(BaseModel):
    encounterNum: int | None = None
    patientNum: int | None = None
    conceptCd: str | None = None
    providerId: str | None = None
    startDate: AwareDatetime | None = None
    modifierCd: str | None = None
    instanceNum: int | None = None
    referenceNum: int | None = None
    referenceChar: str | None = None
    valtypeCd: str | None = None
    tvalChar: str | None = None
    nvalNum: float | None = None
    valueflagCd: str | None = None
    quantityNum: float | None = None
    unitsCd: str | None = None
    endDate: AwareDatetime | None = None
    locationCd: str | None = None
    observationBlob: str | None = None
    sourcesystemCd: str | None = None
    encounterEndYear: int | None = None
    sourceAn: str | None = None
    pseudonymEncounterNum: str | None = None
    pseudonymPatientNum: str | None = None
    pseudonymInstanceNum: str | None = None
    pseudonymReferenceNum: str | None = None
    pseudonymReferenceChar: str | None = None
    isForcePatientLevel: bool | None = None
    pkwithoutModifierCd: str | None = None


class PacsSeriesDTO(BaseModel):
    conceptCd: str | None = None
    label: str | None = None
    pseudonymizedUID: str | None = None
    uid: str | None = None


class PacsStudyDTO(BaseModel):
    pseudonymPatientNum: str | None = None
    pseudonymEncounterNum: str | None = None
    conceptCd: str | None = None
    label: str | None = None
    startDate: date | None = None
    provider: str | None = None
    uid: str | None = None
    pseudonymUid: str | None = None
    series: list[PacsSeriesDTO] | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class IdentityTypeEnum(Enum):
    PATIENT_NUM = 'PATIENT_NUM'
    ENCOUNTER_NUM = 'ENCOUNTER_NUM'
    NIP = 'NIP'
    NDA = 'NDA'


class QueryObservationDTO(BaseModel):
    identityTypeEnum: IdentityTypeEnum | None = None
    pseudonymIdentity: str | None = None
    sexCd: str | None = None
    vitalStatusCd: str | None = None
    lastEncounterStartDate: date | None = None
    countDistinctEncounterNum: int | None = None
    ageLastEncounter: int | None = None
    ageDeath: int | None = None
    yearSinceLastVisit: int | None = None
    tags: list[str] | None = None


class IPseudonymGroupDataAvailableDescription(BaseModel):
    dataSource: str | None = None
    distinctPatientCount: int | None = None
    observationCount: int | None = None


class AdminUserDTO(BaseModel):
    id: str | None = None
    login: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    email: str | None = None
    imageUrl: str | None = None
    activated: bool | None = None
    langKey: str | None = None
    createdBy: str | None = None
    createdDate: AwareDatetime | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: AwareDatetime | None = None
    authorities: list[str] | None = None
    admin: bool | None = None


class PseudonymGroupDescriptionDTO(BaseModel):
    count: int | None = None
    sex: list[ResultAggregateDataDTO] | None = None
    vitalStatus: list[ResultAggregateDataDTO] | None = None
    ageAtLastEncounterDesc: NumericalUnivariateStatisticDTO | None = None
    ageAtLastEncounterHistogram: list[ResultAggregateDataDTO] | None = None
    ageAtDeathDesc: NumericalUnivariateStatisticDTO | None = None
    encounterCountDesc: NumericalUnivariateStatisticDTO | None = None
    yearsSinceLastVisit: list[ResultAggregateDataDTO] | None = None


class PageableObject(BaseModel):
    sort: SortObject | None = None
    offset: int | None = None
    pageNumber: int | None = None
    pageSize: int | None = None
    paged: bool | None = None
    unpaged: bool | None = None


class IdentityObservationDTO(BaseModel):
    pseudonymIdentity: str | None = None
    identityType: IdentityType | None = None
    observations: list[PseudonymObservationDTO] | None = None


class PageIdentityObservationDTO(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    sort: SortObject | None = None
    size: int | None = None
    content: list[IdentityObservationDTO] | None = None
    number: int | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    empty: bool | None = None


class IdentityPacsObservationDTO(BaseModel):
    pseudonymIdentity: str | None = None
    identityType: IdentityType | None = None
    pacsStudies: list[PacsStudyDTO] | None = None


class PageIdentityPacsObservationDTO(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    sort: SortObject | None = None
    size: int | None = None
    content: list[IdentityPacsObservationDTO] | None = None
    number: int | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    empty: bool | None = None


class PageQueryObservationDTO(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    sort: SortObject | None = None
    size: int | None = None
    content: list[QueryObservationDTO] | None = None
    number: int | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    empty: bool | None = None


class PagePseudonymPatientInfoDTO(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    sort: SortObject | None = None
    size: int | None = None
    content: list[PseudonymPatientInfoDTO] | None = None
    number: int | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    empty: bool | None = None
