# generated by datamodel-codegen:
#   filename:  project.json
#   timestamp: 2026-01-23T16:57:48+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class AdminUserDTO(BaseModel):
    activated: bool | None = None
    admin: bool | None = None
    authorities: list[str] | None = Field(None, unique_items=True)
    createdBy: str | None = None
    createdDate: datetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: datetime | None = None
    lastName: str | None = None
    login: str | None = None


class Authority(BaseModel):
    name: str | None = None


class CohortType(Enum):
    ENCOUNTER = 'ENCOUNTER'
    PATIENT = 'PATIENT'


class EdsCohortInfoDTO(BaseModel):
    cohortDescription: str | None = None
    cohortName: str | None = None
    cohortType: CohortType | None = None


class PermissibleFormDTO(BaseModel):
    label: str | None = None
    value: str | None = None


class ProjectLegalMotivationEnum(Enum):
    CONTRACTUAL_OBLIGATION = 'CONTRACTUAL_OBLIGATION'
    LEGAL_OBLIGATION = 'LEGAL_OBLIGATION'
    LEGITIMATE_INTEREST = 'LEGITIMATE_INTEREST'
    PERSONAL_CONSENT = 'PERSONAL_CONSENT'
    PUBLIC_INTEREST = 'PUBLIC_INTEREST'
    PUBLIC_MISSION = 'PUBLIC_MISSION'
    VITAL = 'VITAL'


class ProjectStatu(Enum):
    ADMIN_VALIDATION = 'ADMIN_VALIDATION'
    CREATED = 'CREATED'
    DPO_VALIDATION = 'DPO_VALIDATION'
    IN_PROGRESS = 'IN_PROGRESS'
    IRB_VALIDATION = 'IRB_VALIDATION'
    PI_VALIDATION = 'PI_VALIDATION'
    PROBLEM = 'PROBLEM'
    SUPPRESSED = 'SUPPRESSED'
    TERMINATED = 'TERMINATED'


class PermissibleValuesDTO(BaseModel):
    projectDataUsed: list[PermissibleFormDTO] | None = None
    projectLegalMotivation: list[ProjectLegalMotivationEnum] | None = None
    projectLegalMotivations: list[PermissibleFormDTO] | None = None
    projectMedicalDomain: list[PermissibleFormDTO] | None = None
    projectStatus: list[ProjectStatu] | None = None
    projectType: list[PermissibleFormDTO] | None = None


class ProjectCseCategorizationAssessment(Enum):
    NO = 'NO'
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    YES = 'YES'


class ProjectCseCategorizationContact(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationDiscriminativeData(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationRareDisease(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationRecommendations(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationRetrospective(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationSingleInstitution(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectCseCategorizationStandardCare(Enum):
    NO = 'NO'
    YES = 'YES'


class ProjectDpoDataCategory(Enum):
    BIOMETRIC = 'BIOMETRIC'
    CONNECTION = 'CONNECTION'
    ECONOMIC = 'ECONOMIC'
    ETHNIC = 'ETHNIC'
    GENETIC = 'GENETIC'
    HEALTH = 'HEALTH'
    IDENTIFIER = 'IDENTIFIER'
    IDENTITY = 'IDENTITY'
    JURIDIC = 'JURIDIC'
    LOCALISATION = 'LOCALISATION'
    PERSONAL = 'PERSONAL'
    POLITIC = 'POLITIC'
    PROFESIONAL = 'PROFESIONAL'
    RELIGIOUS = 'RELIGIOUS'
    SEXUALITY = 'SEXUALITY'
    SYNDICATE = 'SYNDICATE'


class ProjectMedicalDomain(Enum):
    ADDICTO = 'ADDICTO'
    ALLERGO = 'ALLERGO'
    ANAPATH = 'ANAPATH'
    ANESTH_REA = 'ANESTH_REA'
    BIOLOGIE = 'BIOLOGIE'
    CANCERO = 'CANCERO'
    CARDIO = 'CARDIO'
    CHIRURGIE = 'CHIRURGIE'
    CHIR_DIH = 'CHIR_DIH'
    CHIR_MAXILLO = 'CHIR_MAXILLO'
    CHIR_NEURO = 'CHIR_NEURO'
    CHIR_ORALE = 'CHIR_ORALE'
    CHIR_ORTHO = 'CHIR_ORTHO'
    CHIR_PEDIA = 'CHIR_PEDIA'
    CHIR_PLASTIQUE = 'CHIR_PLASTIQUE'
    CHIR_THORACIQUE = 'CHIR_THORACIQUE'
    CHIR_VASC = 'CHIR_VASC'
    DERMATO = 'DERMATO'
    ENDOC = 'ENDOC'
    GENETIQUE = 'GENETIQUE'
    GERIATRIE = 'GERIATRIE'
    GYNECO_MED = 'GYNECO_MED'
    GYNECO_OBS = 'GYNECO_OBS'
    HANDICAP = 'HANDICAP'
    HEMATO = 'HEMATO'
    HEPATO = 'HEPATO'
    IMAGERIE = 'IMAGERIE'
    IMMUNO = 'IMMUNO'
    INFECTIO = 'INFECTIO'
    MALADIE_RARE = 'MALADIE_RARE'
    MED_GENERALE = 'MED_GENERALE'
    MED_INTERNE = 'MED_INTERNE'
    MED_LEGALE = 'MED_LEGALE'
    MED_NUCLEAIRE = 'MED_NUCLEAIRE'
    MED_SPORT = 'MED_SPORT'
    MED_TRAVAIL = 'MED_TRAVAIL'
    MPR = 'MPR'
    NEPHRO_URO = 'NEPHRO_URO'
    NEURO = 'NEURO'
    ODONTO = 'ODONTO'
    OPHTALMO = 'OPHTALMO'
    ORL = 'ORL'
    PEDIA = 'PEDIA'
    PNEUMO = 'PNEUMO'
    PSYCHIATRIE = 'PSYCHIATRIE'
    RHUMATO = 'RHUMATO'
    SANTE_PUB = 'SANTE_PUB'
    TOXICO = 'TOXICO'
    TRAUMATO = 'TRAUMATO'
    URG = 'URG'
    VASCULAIRE = 'VASCULAIRE'


class ProjectType(Enum):
    PERTINENCE = 'PERTINENCE'
    RIPH1 = 'RIPH1'
    RIPH2 = 'RIPH2'
    RIPH3 = 'RIPH3'
    RNIPH_MONOCENTRIQUE = 'RNIPH_MONOCENTRIQUE'
    RNIPH_MULTICENTRIQUE = 'RNIPH_MULTICENTRIQUE'
    TEST = 'TEST'
    VIGILANCES = 'VIGILANCES'


class ProjectDataProcessor(BaseModel):
    dpoEmail: str | None = None
    dpoFirstName: str | None = None
    dpoLastName: str | None = None
    entityName: str | None = None


class ProjectWithErrorsDTO(BaseModel):
    startedNoCseDateMailSent: list[str] | None = None
    startedNoCseFormChecked: list[str] | None = None
    startedNoCseMailSent: list[str] | None = None
    startedNoDataUsed: list[str] | None = None
    startedNoIrbSubmission: list[str] | None = None
    startedNoStartDate: list[str] | None = None
    startedNoSynopsis: list[str] | None = None


class Sort(BaseModel):
    empty: bool | None = None
    sorted: bool | None = None
    unsorted: bool | None = None


class User(BaseModel):
    activated: bool | None = None
    authorities: list[Authority] | None = Field(None, unique_items=True)
    createdBy: str | None = None
    createdDate: datetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: datetime | None = None
    lastName: str | None = None
    login: str | None = None


class UserDTO(BaseModel):
    id: str | None = None
    login: str | None = None


class UserRoles(BaseModel):
    PROJECT_ACCESS_MAPPING_TABLE: bool | None = None
    PROJECT_ACCESS_PSEUDONYM_DATA: bool | None = None
    PROJECT_ADD_IDENTITY: bool | None = None
    PROJECT_ADMINISTRATION: bool | None = None
    PROJECT_EXECUTE_QUERY: bool | None = None
    PROJECT_MANAGE_REDCAP: bool | None = None
    PROJECT_MANAGE_SMART_CRF: bool | None = None
    activated: bool | None = None
    authorities: list[Authority] | None = Field(None, unique_items=True)
    createdBy: str | None = None
    createdDate: datetime | None = None
    email: str | None = None
    firstName: str | None = None
    id: str | None = None
    imageUrl: str | None = None
    langKey: str | None = None
    lastModifiedBy: str | None = None
    lastModifiedDate: datetime | None = None
    lastName: str | None = None
    login: str | None = None


class Project(BaseModel):
    cohortId: str | None = None
    id: str | None = None
    projectAsAccessToSourceIdentity: bool | None = None
    projectCreationChecked: bool | None = None
    projectCreationDate: datetime | None = None
    projectCreator: User | None = None
    projectCseCategorizationAssessment: ProjectCseCategorizationAssessment | None = None
    projectCseCategorizationContact: ProjectCseCategorizationContact | None = None
    projectCseCategorizationDiscriminativeData: (
        ProjectCseCategorizationDiscriminativeData | None
    ) = None
    projectCseCategorizationRareDisease: ProjectCseCategorizationRareDisease | None = (
        None
    )
    projectCseCategorizationRecommendations: (
        ProjectCseCategorizationRecommendations | None
    ) = None
    projectCseCategorizationRetrospective: (
        ProjectCseCategorizationRetrospective | None
    ) = None
    projectCseCategorizationSingleInstitution: (
        ProjectCseCategorizationSingleInstitution | None
    ) = None
    projectCseCategorizationStandardCare: (
        ProjectCseCategorizationStandardCare | None
    ) = None
    projectCseCode: str | None = None
    projectCseContext: str | None = None
    projectCseDataCollected: str | None = None
    projectCseDataCollectionMethods: str | None = None
    projectCseDataOrigin: str | None = None
    projectCseDataProtection: str | None = None
    projectCseDataStorage: str | None = None
    projectCseEvaluationCriteria: str | None = None
    projectCseFormChecked: bool | None = None
    projectCseInclusionCriteria: str | None = None
    projectCseMailSend: bool | None = None
    projectCseMailSendDate: datetime | None = None
    projectCseNonInclusionCriteria: str | None = None
    projectCsePatientInformation: str | None = None
    projectCseRecordDate: datetime | None = None
    projectCseStatement: str | None = None
    projectCseStatementContentType: str | None = None
    projectCseStudyDuration: str | None = None
    projectCseStudyObjectives: str | None = None
    projectCseStudyOrganisation: str | None = None
    projectCseStudyOutcomes: str | None = None
    projectCseStudySize: str | None = None
    projectCseStudyStatistics: str | None = None
    projectCseStudyType: str | None = None
    projectCseSynopsisFile: str | None = None
    projectCseSynopsisFileContentType: str | None = None
    projectDpoCode: str | None = None
    projectDpoDataCategories: list[ProjectDpoDataCategory] | None = None
    projectDpoDataCategoriesLabel: list[str] | None = None
    projectDpoNumber: int | None = None
    projectDpoRecordDate: datetime | None = None
    projectEdsDataUsed: list[str] | None = None
    projectEndDate: datetime | None = None
    projectExternalDataProcessors: list[ProjectDataProcessor] | None = None
    projectInstitutionalCode: str | None = None
    projectLegalMotivation: list[ProjectLegalMotivationEnum] | None = None
    projectLegalMotivationLabel: list[str] | None = None
    projectMedicalDomain: ProjectMedicalDomain | None = None
    projectMedicalDomainLabel: str | None = None
    projectName: str | None = None
    projectParticipants: list[UserRoles] | None = Field(None, unique_items=True)
    projectPartners: str | None = None
    projectPrincipalDataProcessors: list[ProjectDataProcessor] | None = None
    projectPrincipalInvestigator: User | None = None
    projectPublicAbstract: str | None = None
    projectScientificAbstract: str | None = None
    projectShortName: str | None = None
    projectStartDate: datetime | None = None
    projectStatus: str | None = None
    projectStatusCREATED: bool | None = None
    projectStatusDPO_VALIDATION: bool | None = None
    projectStatusIN_PROGRESS: bool | None = None
    projectStatusIRB_CATEGORIZATION: bool | None = None
    projectStatusIRB_SUBMISSION: bool | None = None
    projectStatusIRB_SYNOPSIS: bool | None = None
    projectStatusIRB_VALIDATION: bool | None = None
    projectStatusLabel: str | None = None
    projectStatusPI_VALIDATION: bool | None = None
    projectStatusSUPRESSED: bool | None = None
    projectStatusTERMINATED: bool | None = None
    projectType: ProjectType | None = None
    projectTypeLabel: str | None = None
    projectUpdateDate: datetime | None = None


class ProjectDTO(BaseModel):
    canAddDataInCohort: bool | None = None
    canAddDataToRedcap: bool | None = None
    canAddIRB: bool | None = None
    canAddIRBInfo: bool | None = None
    canAdministrate: bool | None = None
    canDelete: bool | None = None
    canDeleteIRB: bool | None = None
    canDepseudonymize: bool | None = None
    canEdit: bool | None = None
    canEditPi: bool | None = None
    canEditProjectType: bool | None = None
    canExecuteQueryInProject: bool | None = None
    canInvalidate: bool | None = None
    canManageRedCap: bool | None = None
    canManageSmartCrf: bool | None = None
    canRestart: bool | None = None
    canRestore: bool | None = None
    canSeeIndividualData: bool | None = None
    canSendDPO: bool | None = None
    canStart: bool | None = None
    canTerminate: bool | None = None
    canValidate: bool | None = None
    canView: bool | None = None
    cohortId: str | None = None
    completeCSeSynopsisForm: bool | None = None
    currentStep: str | None = None
    id: str | None = None
    projectAsAccessToSourceIdentity: bool | None = None
    projectCreationChecked: bool | None = None
    projectCreationComplete: bool | None = None
    projectCreationDate: datetime | None = None
    projectCreator: User | None = None
    projectCseCategorizationAssessment: ProjectCseCategorizationAssessment | None = None
    projectCseCategorizationContact: ProjectCseCategorizationContact | None = None
    projectCseCategorizationDiscriminativeData: (
        ProjectCseCategorizationDiscriminativeData | None
    ) = None
    projectCseCategorizationRareDisease: ProjectCseCategorizationRareDisease | None = (
        None
    )
    projectCseCategorizationRecommendations: (
        ProjectCseCategorizationRecommendations | None
    ) = None
    projectCseCategorizationRetrospective: (
        ProjectCseCategorizationRetrospective | None
    ) = None
    projectCseCategorizationSingleInstitution: (
        ProjectCseCategorizationSingleInstitution | None
    ) = None
    projectCseCategorizationStandardCare: (
        ProjectCseCategorizationStandardCare | None
    ) = None
    projectCseCode: str | None = None
    projectCseContext: str | None = None
    projectCseDataCollected: str | None = None
    projectCseDataCollectionMethods: str | None = None
    projectCseDataOrigin: str | None = None
    projectCseDataProtection: str | None = None
    projectCseDataStorage: str | None = None
    projectCseEvaluationCriteria: str | None = None
    projectCseFormChecked: bool | None = None
    projectCseFormComplete: bool | None = None
    projectCseInclusionCriteria: str | None = None
    projectCseMailSend: bool | None = None
    projectCseMailSendDate: datetime | None = None
    projectCseNonInclusionCriteria: str | None = None
    projectCsePatientInformation: str | None = None
    projectCseRecordDate: datetime | None = None
    projectCseStatement: str | None = None
    projectCseStatementContentType: str | None = None
    projectCseStudyDuration: str | None = None
    projectCseStudyObjectives: str | None = None
    projectCseStudyOrganisation: str | None = None
    projectCseStudyOutcomes: str | None = None
    projectCseStudySize: str | None = None
    projectCseStudyStatistics: str | None = None
    projectCseStudyType: str | None = None
    projectCseSynopsisFile: str | None = None
    projectCseSynopsisFileContentType: str | None = None
    projectDPOFormComplete: bool | None = None
    projectDpoCode: str | None = None
    projectDpoDataCategories: list[ProjectDpoDataCategory] | None = None
    projectDpoDataCategoriesLabel: list[str] | None = None
    projectDpoNumber: int | None = None
    projectDpoRecordDate: datetime | None = None
    projectEdsDataUsed: list[str] | None = None
    projectEndDate: datetime | None = None
    projectExternalDataProcessors: list[ProjectDataProcessor] | None = None
    projectInstitutionalCode: str | None = None
    projectLegalMotivation: list[ProjectLegalMotivationEnum] | None = None
    projectLegalMotivationLabel: list[str] | None = None
    projectMedicalDomain: ProjectMedicalDomain | None = None
    projectMedicalDomainLabel: str | None = None
    projectName: str | None = None
    projectParticipants: list[UserRoles] | None = Field(None, unique_items=True)
    projectPartners: str | None = None
    projectPrincipalDataProcessors: list[ProjectDataProcessor] | None = None
    projectPrincipalInvestigator: User | None = None
    projectPublicAbstract: str | None = None
    projectScientificAbstract: str | None = None
    projectShortName: str | None = None
    projectStartDate: datetime | None = None
    projectStatus: str | None = None
    projectStatusCREATED: bool | None = None
    projectStatusDPO_VALIDATION: bool | None = None
    projectStatusIN_PROGRESS: bool | None = None
    projectStatusIRB_CATEGORIZATION: bool | None = None
    projectStatusIRB_SUBMISSION: bool | None = None
    projectStatusIRB_SYNOPSIS: bool | None = None
    projectStatusIRB_VALIDATION: bool | None = None
    projectStatusLabel: str | None = None
    projectStatusPI_VALIDATION: bool | None = None
    projectStatusSUPRESSED: bool | None = None
    projectStatusTERMINATED: bool | None = None
    projectType: ProjectType | None = None
    projectTypeLabel: str | None = None
    projectUpdateDate: datetime | None = None


class PageOfProject(BaseModel):
    content: list[Project] | None = None
    empty: bool | None = None
    first: bool | None = None
    last: bool | None = None
    number: int | None = None
    numberOfElements: int | None = None
    size: int | None = None
    sort: Sort | None = None
    totalElements: int | None = None
    totalPages: int | None = None


class PageOfProjectDTO(BaseModel):
    content: list[ProjectDTO] | None = None
    empty: bool | None = None
    first: bool | None = None
    last: bool | None = None
    number: int | None = None
    numberOfElements: int | None = None
    size: int | None = None
    sort: Sort | None = None
    totalElements: int | None = None
    totalPages: int | None = None
