# generated by datamodel-codegen:
#   filename:  .ipynb_checkpoints/redcap-checkpoint.json
#   timestamp: 2026-01-23T20:30:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Purpose(Enum):
    OPERATIONAL_SUPPORT = 'OPERATIONAL_SUPPORT'
    OTHER = 'OTHER'
    PRACTICE = 'PRACTICE'
    QUALITY_IMPROVEMENT = 'QUALITY_IMPROVEMENT'
    RESEARCH = 'RESEARCH'


class RedCAPInstanceEnum(Enum):
    CHU_REDCAP = 'CHU_REDCAP'
    IAMREDCAP = 'IAMREDCAP'
    IHUREDCAP = 'IHUREDCAP'
    USMR_REDCAP = 'USMR_REDCAP'


class REDCapProject(BaseModel):
    fieldCount: int | None = None
    instrumentCount: int | None = None
    pid: int | None = None
    projectNotes: str | None = None
    projectTitle: str | None = None
    purpose: Purpose | None = None
    purposeOther: str | None = None
    recordCount: int | None = None
    redCAPInstanceEnum: RedCAPInstanceEnum | None = None
    token: str | None = None
    url: str | None = None
    version: str | None = None


class REDCapProjectCreationDTO(BaseModel):
    projectNotes: str | None = None
    projectTitle: str | None = None
    purpose: Purpose | None = None
    purposeOther: str | None = None
